sudo: required
dist: trusty
language: generic
env:
  matrix:
    - ROS_DISTRO="kinetic"   REPOSITORY=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic"   REPOSITORY=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - case $ROS_DISTRO in "hydro") export DISTRO=precise;; "indigo") export DISTRO=trusty;; "kinetic") export DISTRO=xenial;; esac;
  - export DOCKER_IMAGE=ubuntu:$DISTRO
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - docker images
  - docker run -v $HOME:$HOME -e CI_SOURCE_PATH -e $REPOSITORY_NAME -e HOME -e DISTRO -e ROS_DISTRO -e REPOSITORY $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_PATH; source .travis.sh'
